export type ScreenKey = "today" | "classes" | "coach" | "inbox" | "more";

export type ClassItem = {
  id: string;
  dayKey: string;
  dayLabel: string;
  time: string;
  pool: string;
  level: string;
  students: number;
  attendance: string;
  badges: string[];
  focus: string;
  equipment: string[];
  safety: string[];
  handover: string;
  studentIds: string[];
};

export type StudentItem = {
  id: string;
  classId: string;
  name: string;
  age: number;
  level: string;
  type: string;
  focus: string;
  lastAttended: string;
  parent: string;
  parentPhone: string;
  safety: string;
  progress: Array<[string, string]>;
  readiness: string;
  note: string;
  currentTestLevel: string;
  studentStatus: string;
  equipmentStatus: string;
  paymentStatus: string;
  pauseQuitStatus: string;
};

export type NotificationItem = {
  title: string;
  meta: string;
  body: string;
  variant: "" | "yellow" | "alert" | "success";
};

export const coach = {
  name: "Coach Ryan",
  classesToday: 4,
  firstClass: "9:00 AM",
  location: "Bishan",
};

export const classes: ClassItem[] = [
  {
    id: "class-stage-2-sat-9",
    dayKey: "sat",
    dayLabel: "Saturday",
    time: "9:00 AM - 9:45 AM",
    pool: "Bishan",
    level: "Stage 2",
    students: 6,
    attendance: "Not marked",
    badges: ["Starting Soon", "Cover Class", "Affected by Alert"],
    focus: "Breathing control, stamina, and floating confidence",
    equipment: ["Kickboards x6", "Noodles x6", "Sink toys x4", "Cones x2"],
    safety: [
      "Jayden needs extra encouragement with side breathing.",
      "Chloe is new and may be afraid of deeper water.",
    ],
    handover:
      "Coach Aisyah is on leave. Please reassure Chloe before entry and watch Aiden's pacing.",
    studentIds: ["jayden", "aiden", "chloe", "sophie", "ethan", "grace"],
  },
  {
    id: "class-stage-1-sat-10",
    dayKey: "sat",
    dayLabel: "Saturday",
    time: "10:30 AM - 11:15 AM",
    pool: "Bishan",
    level: "Stage 1",
    students: 5,
    attendance: "Pending submission",
    badges: ["Attendance Pending", "Progress Pending"],
    focus: "Water confidence, floating, and safe entry",
    equipment: ["Kickboards x5", "Toy cups x5", "Noodles x5"],
    safety: ["One trial student needs gentle introduction to the pool."],
    handover:
      "Parent asked for stamina update after class. Trial student Chloe to be assessed for Stage 1 fit.",
    studentIds: ["isla", "ryan-jr", "mei", "arjun", "noah"],
  },
  {
    id: "class-stage-3-sun-9",
    dayKey: "sun",
    dayLabel: "Sunday",
    time: "9:00 AM - 9:45 AM",
    pool: "Bishan",
    level: "Stage 3",
    students: 5,
    attendance: "Ready",
    badges: ["Test Window"],
    focus: "Freestyle rhythm and breathing endurance",
    equipment: ["Kickboards x5", "Pull buoys x5", "Fins x5"],
    safety: ["Keep trial swimmers in Lane 1 until warm-up is complete."],
    handover: "Two students may be ready for Stage 3 test sign-off this weekend.",
    studentIds: ["nora", "kai", "luke", "hannah", "owen"],
  },
  {
    id: "class-stage-2-sun-11",
    dayKey: "sun",
    dayLabel: "Sunday",
    time: "11:15 AM - 12:00 PM",
    pool: "Sengkang",
    level: "Stage 2",
    students: 4,
    attendance: "Ready",
    badges: ["Transfer Option"],
    focus: "Confidence in longer sets and side breathing",
    equipment: ["Kickboards x4", "Noodles x4"],
    safety: ["One student prefers lane-end starts instead of wall push-offs."],
    handover: "Steady group. Suitable transfer destination for Stage 2 swimmers.",
    studentIds: ["amelia", "zane", "ivy", "ben"],
  },
  {
    id: "class-land-drill-sat-11",
    dayKey: "sat",
    dayLabel: "Saturday",
    time: "11:15 AM - 12:00 PM",
    pool: "Sheltered Waiting Area",
    level: "Mixed Stage 2",
    students: 8,
    attendance: "Ready",
    badges: ["Land Drill Required"],
    focus: "Dry kicking, breathing rhythm, and safety quiz",
    equipment: ["Cones x4", "Visual cards x8"],
    safety: ["Keep students seated under shelter until pool is cleared."],
    handover: "Use land drill set A until admin sends resume notice.",
    studentIds: [],
  },
];

export const students: StudentItem[] = [
  {
    id: "jayden",
    classId: "class-stage-2-sat-9",
    name: "Jayden Tan",
    age: 7,
    level: "Stage 2",
    type: "Regular Student",
    focus: "Breathing control and stamina",
    lastAttended: "18 May 2026",
    parent: "Jayden's Parent",
    parentPhone: "+65 8123 4551",
    safety: "Sensitive to cold water. Parent requested gentle approach.",
    progress: [
      ["Breathing control", "Improving"],
      ["Floating", "Can Do Independently"],
      ["Kicking", "Needs More Practice"],
    ],
    readiness: "Flag Ready Soon",
    note:
      "Jayden is improving in stamina but still needs more side breathing repetition.",
    currentTestLevel: "SwimSafer Stage 2",
    studentStatus: "Active",
    equipmentStatus: "Swim Cap Pending",
    paymentStatus: "Paid",
    pauseQuitStatus: "None",
  },
  {
    id: "aiden",
    classId: "class-stage-2-sat-9",
    name: "Aiden Lim",
    age: 8,
    level: "Stage 2",
    type: "Replacement Student",
    focus: "Water confidence and pacing",
    lastAttended: "19 May 2026",
    parent: "Aiden's Parent",
    parentPhone: "+65 9876 4452",
    safety: "Today at Bishan. Usual pool is Sengkang.",
    progress: [
      ["Kick timing", "Improving"],
      ["Floating", "Ready for Next Level"],
      ["Confidence", "Strong"],
    ],
    readiness: "Needs More Practice",
    note: "Replacement student today. Needs a quick orientation before class starts.",
    currentTestLevel: "Internal 200M",
    studentStatus: "Replacement",
    equipmentStatus: "Not Required",
    paymentStatus: "Payment Not Sent",
    pauseQuitStatus: "Pending Pause",
  },
  {
    id: "chloe",
    classId: "class-stage-2-sat-9",
    name: "Chloe Tan",
    age: 6,
    level: "Trial Beginner",
    type: "Trial Student",
    focus: "Build comfort and confidence",
    lastAttended: "First class today",
    parent: "Chloe's Parent",
    parentPhone: "+65 9333 1200",
    safety: "Afraid of deep water. Needs reassurance before entering the pool.",
    progress: [
      ["Water confidence", "Learning"],
      ["Floating", "Not Started"],
      ["Listening", "Strong"],
    ],
    readiness: "Suitable for Stage 1",
    note: "Comfortable under guidance. Recommend Stage 1 after trial if confidence improves.",
    currentTestLevel: "Trial Beginner",
    studentStatus: "Trial",
    equipmentStatus: "Goggles Pending",
    paymentStatus: "Trial",
    pauseQuitStatus: "None",
  },
  {
    id: "sophie",
    classId: "class-stage-2-sat-9",
    name: "Sophie Ng",
    age: 7,
    level: "Stage 2",
    type: "Regular Student",
    focus: "Breathing timing and streamline",
    lastAttended: "17 May 2026",
    parent: "Sophie's Parent",
    parentPhone: "+65 8110 2203",
    safety: "None reported.",
    progress: [
      ["Breathing control", "Strong"],
      ["Floating", "Strong"],
      ["Kicking", "Improving"],
    ],
    readiness: "Ready for Assessment",
    note: "Confident swimmer. Good candidate for next assessment slot.",
    currentTestLevel: "SwimSafer Stage 2",
    studentStatus: "Active",
    equipmentStatus: "Not Required",
    paymentStatus: "Paid",
    pauseQuitStatus: "None",
  },
  {
    id: "ethan",
    classId: "class-stage-2-sat-9",
    name: "Ethan Koh",
    age: 8,
    level: "Stage 2",
    type: "Regular Student",
    focus: "Endurance and side breathing",
    lastAttended: "18 May 2026",
    parent: "Ethan's Parent",
    parentPhone: "+65 8222 1108",
    safety: "Wears prescription goggles.",
    progress: [
      ["Breathing control", "Improving"],
      ["Floating", "Can Do Independently"],
      ["Kicking", "Improving"],
    ],
    readiness: "On Track",
    note: "Responds well to short repetition blocks and direct cues.",
    currentTestLevel: "SwimSafer Stage 2",
    studentStatus: "Active",
    equipmentStatus: "Not Required",
    paymentStatus: "Paid",
    pauseQuitStatus: "None",
  },
  {
    id: "grace",
    classId: "class-stage-2-sat-9",
    name: "Grace Teo",
    age: 7,
    level: "Stage 2",
    type: "Regular Student",
    focus: "Confidence in longer laps",
    lastAttended: "18 May 2026",
    parent: "Grace's Parent",
    parentPhone: "+65 8555 6601",
    safety: "Prefers lane-end reminders before each drill change.",
    progress: [
      ["Breathing control", "Improving"],
      ["Floating", "Strong"],
      ["Kicking", "Strong"],
    ],
    readiness: "Needs More Practice",
    note: "Good body position. Still loses rhythm under fatigue.",
    currentTestLevel: "SwimSafer Stage 2",
    studentStatus: "Active",
    equipmentStatus: "Not Required",
    paymentStatus: "Paid",
    pauseQuitStatus: "None",
  },
  {
    id: "isla",
    classId: "class-stage-1-sat-10",
    name: "Isla Wong",
    age: 6,
    level: "Stage 1",
    type: "Regular Student",
    focus: "Floating confidence",
    lastAttended: "18 May 2026",
    parent: "Isla's Parent",
    parentPhone: "+65 8011 3340",
    safety: "Needs extra encouragement at entry.",
    progress: [["Floating", "Improving"]],
    readiness: "On Track",
    note: "Settles well after warm-up.",
    currentTestLevel: "SwimSafer Stage 1",
    studentStatus: "Active",
    equipmentStatus: "Not Required",
    paymentStatus: "Paid",
    pauseQuitStatus: "None",
  },
  {
    id: "ryan-jr",
    classId: "class-stage-1-sat-10",
    name: "Ryan Chua",
    age: 5,
    level: "Stage 1",
    type: "Regular Student",
    focus: "Safe entry and blowing bubbles",
    lastAttended: "18 May 2026",
    parent: "Ryan's Parent",
    parentPhone: "+65 8333 7720",
    safety: "None reported.",
    progress: [["Water confidence", "Learning"]],
    readiness: "On Track",
    note: "Doing well with short turns.",
    currentTestLevel: "SwimSafer Stage 1",
    studentStatus: "Active",
    equipmentStatus: "Not Required",
    paymentStatus: "Paid",
    pauseQuitStatus: "None",
  },
  {
    id: "mei",
    classId: "class-stage-1-sat-10",
    name: "Mei Lin",
    age: 6,
    level: "Stage 1",
    type: "Regular Student",
    focus: "Floating and breath control",
    lastAttended: "17 May 2026",
    parent: "Mei's Parent",
    parentPhone: "+65 9001 5541",
    safety: "None reported.",
    progress: [["Breathing control", "Improving"]],
    readiness: "On Track",
    note: "Steady progress each week.",
    currentTestLevel: "SwimSafer Stage 1",
    studentStatus: "Active",
    equipmentStatus: "Not Required",
    paymentStatus: "Paid",
    pauseQuitStatus: "None",
  },
  {
    id: "arjun",
    classId: "class-stage-1-sat-10",
    name: "Arjun Nair",
    age: 6,
    level: "Stage 1",
    type: "Regular Student",
    focus: "Water confidence",
    lastAttended: "18 May 2026",
    parent: "Arjun's Parent",
    parentPhone: "+65 8440 3312",
    safety: "None reported.",
    progress: [["Confidence", "Improving"]],
    readiness: "On Track",
    note: "Benefits from demo-first coaching.",
    currentTestLevel: "SwimSafer Stage 1",
    studentStatus: "Active",
    equipmentStatus: "Not Required",
    paymentStatus: "Paid",
    pauseQuitStatus: "None",
  },
  {
    id: "noah",
    classId: "class-stage-1-sat-10",
    name: "Noah Sim",
    age: 5,
    level: "Stage 1",
    type: "Regular Student",
    focus: "Kicking and safe entry",
    lastAttended: "17 May 2026",
    parent: "Noah's Parent",
    parentPhone: "+65 8771 2219",
    safety: "None reported.",
    progress: [["Kicking", "Learning"]],
    readiness: "On Track",
    note: "Needs frequent reset between drills.",
    currentTestLevel: "SwimSafer Stage 1",
    studentStatus: "Active",
    equipmentStatus: "Not Required",
    paymentStatus: "Paid",
    pauseQuitStatus: "None",
  },
  {
    id: "nora",
    classId: "class-stage-3-sun-9",
    name: "Nora Lee",
    age: 9,
    level: "Stage 3",
    type: "Regular Student",
    focus: "Freestyle rhythm",
    lastAttended: "18 May 2026",
    parent: "Nora's Parent",
    parentPhone: "+65 8112 5559",
    safety: "None reported.",
    progress: [["Freestyle", "Strong"]],
    readiness: "Ready for Assessment",
    note: "Consistent pace.",
    currentTestLevel: "SwimSafer Stage 3",
    studentStatus: "Active",
    equipmentStatus: "Not Required",
    paymentStatus: "Paid",
    pauseQuitStatus: "None",
  },
  {
    id: "kai",
    classId: "class-stage-3-sun-9",
    name: "Kai Ho",
    age: 9,
    level: "Stage 3",
    type: "Regular Student",
    focus: "Freestyle breathing",
    lastAttended: "18 May 2026",
    parent: "Kai's Parent",
    parentPhone: "+65 8221 0017",
    safety: "None reported.",
    progress: [["Freestyle", "Improving"]],
    readiness: "On Track",
    note: "Needs cleaner recovery arm.",
    currentTestLevel: "SwimSafer Stage 3",
    studentStatus: "Active",
    equipmentStatus: "Not Required",
    paymentStatus: "Paid",
    pauseQuitStatus: "None",
  },
  {
    id: "luke",
    classId: "class-stage-3-sun-9",
    name: "Luke Tan",
    age: 8,
    level: "Stage 3",
    type: "Regular Student",
    focus: "Endurance",
    lastAttended: "17 May 2026",
    parent: "Luke's Parent",
    parentPhone: "+65 8332 1107",
    safety: "None reported.",
    progress: [["Endurance", "Improving"]],
    readiness: "On Track",
    note: "Good pool awareness.",
    currentTestLevel: "SwimSafer Stage 3",
    studentStatus: "Active",
    equipmentStatus: "Not Required",
    paymentStatus: "Paid",
    pauseQuitStatus: "None",
  },
  {
    id: "hannah",
    classId: "class-stage-3-sun-9",
    name: "Hannah Ong",
    age: 9,
    level: "Stage 3",
    type: "Regular Student",
    focus: "Timing and turns",
    lastAttended: "18 May 2026",
    parent: "Hannah's Parent",
    parentPhone: "+65 8991 4402",
    safety: "None reported.",
    progress: [["Turns", "Improving"]],
    readiness: "On Track",
    note: "Strong attention to cues.",
    currentTestLevel: "SwimSafer Stage 3",
    studentStatus: "Active",
    equipmentStatus: "Not Required",
    paymentStatus: "Paid",
    pauseQuitStatus: "None",
  },
  {
    id: "owen",
    classId: "class-stage-3-sun-9",
    name: "Owen Foo",
    age: 8,
    level: "Stage 3",
    type: "Regular Student",
    focus: "Breathing rhythm",
    lastAttended: "18 May 2026",
    parent: "Owen's Parent",
    parentPhone: "+65 8663 9994",
    safety: "None reported.",
    progress: [["Breathing control", "Improving"]],
    readiness: "Needs More Practice",
    note: "Fatigues late in session.",
    currentTestLevel: "SwimSafer Stage 3",
    studentStatus: "Active",
    equipmentStatus: "Not Required",
    paymentStatus: "Paid",
    pauseQuitStatus: "None",
  },
  {
    id: "amelia",
    classId: "class-stage-2-sun-11",
    name: "Amelia Goh",
    age: 7,
    level: "Stage 2",
    type: "Regular Student",
    focus: "Side breathing",
    lastAttended: "18 May 2026",
    parent: "Amelia's Parent",
    parentPhone: "+65 8118 2207",
    safety: "None reported.",
    progress: [["Breathing control", "Improving"]],
    readiness: "On Track",
    note: "Transfer-friendly classmate profile.",
    currentTestLevel: "SwimSafer Stage 2",
    studentStatus: "Active",
    equipmentStatus: "Not Required",
    paymentStatus: "Paid",
    pauseQuitStatus: "None",
  },
  {
    id: "zane",
    classId: "class-stage-2-sun-11",
    name: "Zane Loh",
    age: 8,
    level: "Stage 2",
    type: "Regular Student",
    focus: "Stamina",
    lastAttended: "18 May 2026",
    parent: "Zane's Parent",
    parentPhone: "+65 8128 4441",
    safety: "None reported.",
    progress: [["Endurance", "Improving"]],
    readiness: "On Track",
    note: "Steady swimmer.",
    currentTestLevel: "SwimSafer Stage 2",
    studentStatus: "Active",
    equipmentStatus: "Not Required",
    paymentStatus: "Paid",
    pauseQuitStatus: "None",
  },
  {
    id: "ivy",
    classId: "class-stage-2-sun-11",
    name: "Ivy Tan",
    age: 7,
    level: "Stage 2",
    type: "Regular Student",
    focus: "Confidence",
    lastAttended: "18 May 2026",
    parent: "Ivy's Parent",
    parentPhone: "+65 8448 5530",
    safety: "None reported.",
    progress: [["Confidence", "Strong"]],
    readiness: "On Track",
    note: "Positive class fit.",
    currentTestLevel: "SwimSafer Stage 2",
    studentStatus: "Active",
    equipmentStatus: "Not Required",
    paymentStatus: "Paid",
    pauseQuitStatus: "None",
  },
  {
    id: "ben",
    classId: "class-stage-2-sun-11",
    name: "Ben Yeo",
    age: 8,
    level: "Stage 2",
    type: "Regular Student",
    focus: "Breathing rhythm",
    lastAttended: "18 May 2026",
    parent: "Ben's Parent",
    parentPhone: "+65 8550 2199",
    safety: "None reported.",
    progress: [["Breathing control", "Improving"]],
    readiness: "On Track",
    note: "Settles in quickly.",
    currentTestLevel: "SwimSafer Stage 2",
    studentStatus: "Active",
    equipmentStatus: "Not Required",
    paymentStatus: "Paid",
    pauseQuitStatus: "None",
  },
];

export const notifications: NotificationItem[] = [
  {
    title: "Lightning alert at Bishan",
    meta: "Urgent • Safety",
    body: "Water activity should pause now. Move students to sheltered area and wait for update.",
    variant: "alert",
  },
  {
    title: "New student added to 10:30 AM class",
    meta: "Action Required • Students",
    body: "Chloe Tan is attending her first class today. Review the parent concern before class.",
    variant: "yellow",
  },
  {
    title: "Equipment issue acknowledged",
    meta: "For Information • Admin",
    body: "Admin received the missing kickboards report and is checking storage.",
    variant: "success",
  },
  {
    title: "Attendance has not been submitted",
    meta: "Action Required • Attendance",
    body: "Please mark attendance before ending the 10:30 AM Stage 1 class.",
    variant: "",
  },
];
